export const TASKS = [
  {
    id: 't1',
    title: 'Data Structures Assignment',
    due: 'Today · 2:00 PM',
    filter: 'today',
    priority: 'High',
    category: 'Computer Science',
    notes: 'Implement a balanced binary search tree with insert, delete, and in-order traversal. Submit via the course portal by 2 PM.',
    completed: false,
  },
  {
    id: 't2',
    title: 'Signals & Systems Quiz',
    due: 'Today · 5:00 PM',
    filter: 'today',
    priority: 'Medium',
    category: 'Electronics',
    notes: 'Covers Fourier transforms and convolution — review lecture 8 and 9 slides.',
    completed: false,
  },
  {
    id: 't3',
    title: 'Linear Algebra Practice',
    due: 'Tomorrow · 8:00 PM',
    filter: 'tomorrow',
    priority: 'Low',
    category: 'Mathematics',
    notes: 'Practice set 4: eigenvalues and eigenvectors, problems 1-12.',
    completed: false,
  },
  {
    id: 't4',
    title: 'Read Chapter 4',
    due: 'Wed · 6:00 PM',
    filter: 'upcoming',
    priority: 'Low',
    category: 'Database Systems',
    notes: 'Normalization and the third normal form. Take notes on the key definitions.',
    completed: false,
  },
  {
    id: 't5',
    title: 'OS Lab Report',
    due: 'Thu · 11:59 PM',
    filter: 'upcoming',
    priority: 'High',
    category: 'Operating Systems',
    notes: 'Write up the memory management simulation results. Include screenshots from the scheduler output.',
    completed: false,
  },
  {
    id: 't6',
    title: 'Calculus Problem Set',
    due: 'Fri · 10:00 AM',
    filter: 'upcoming',
    priority: 'Medium',
    category: 'Mathematics',
    notes: 'Chapter 7 exercises — integration by parts and substitution. Show all working.',
    completed: false,
  },
  {
    id: 't7',
    title: 'Physics Lab Pre-Report',
    due: 'Last week',
    filter: 'done',
    priority: 'High',
    category: 'Physics',
    notes: 'Submitted. Covered velocity and acceleration graphs for the inclined plane experiment.',
    completed: true,
  },
  {
    id: 't8',
    title: 'English Essay Draft',
    due: 'Last Monday',
    filter: 'done',
    priority: 'Medium',
    category: 'English',
    notes: 'First draft submitted. Peer review session scheduled for next week.',
    completed: true,
  },
];

export const TASK_FILTERS = ['today', 'tomorrow', 'upcoming', 'done'];
